_includes/google_analytics.html

https://support.google.com/business/answer/4569085?p=link_page_to_website&rd=2

Because Google Verification Sucks

---

about/rules_and_policies.md

rm dup line and add 'at own risk' statement re project storage

Speedy update

---

about/press.md

Years descending from top, add DIY Citizenship, and remove implicit invite to press.

rearrange and update

---

events/how-to-start-a-class.md

https://twitter.com/belfastjs/status/575650340739096576

MINOR: Update Belfast JS

---

about/club_mate.md

Basic Club-Mate about page, with information about what's in the space, and how to order some.

Added Club-Mate about page

---

README.md

The `README.md` has been updated with new guidelines on contribution to the project.

Rewrite of contribution guidelines

---

README.md
about/club_mate.md

@Stealthii are your changes ready?

Documentation + Mate Update

---

about/ops_manual.md

To be discussed and ideally ratified at next town hall (7/9/15)

Development NEM Initial Suggestions

---

about/club_mate.md

Added details on how to purchase, link to mailing list, and prices.

Club mate information updates

---

events/raspberry_jam.md

EID failure is Eventbrites fault.

Add Jam link for when things go wrong with EIDs

---

about/corporates.md
about/index.html

Drop Intel and ABPNI corporate support

---

events/how-to-start-a-class.md
events/index.html

Add room availability calendar to events listings

room-booking

---

about/expenses_purchasing.md

https://docs.google.com/document/d/1mCw2LVXB_xd31DPGGf7hRXy6rhpfvICw56uv2NIe8Vk/edit#

As cleared from Town Hall

---

membership/index.md

Fix for MO-63, tweaking Freelancer language and moving daypass CTA into main join page.

Updated and rebased to avoid munging master

---

_config.yml

Jekyll 3 compatibility

---

events/raspberry_jam.md

- Update tickets link
- Add out of tickets section
- Remove summer break banner

Update Raspberry Jam page

---

_layouts/default.html

Update averagehuman home page

---

_config.yml

Updating my bio section to remove old job and correct role description.

Update Claire bio

---

about/expenses_purchasing.md

Amend link from https://help.xero.com/uk/Q_ExpenseClaims%24BK_Steps
which is a 404 to https://help.xero.com/uk/Payments_ExpenseClaims
which may or may not have similar content.

Decrement number of broken links on expenses page

---

index.html

As part of my seemingly endless procession of meetings, one thing was recurring more than usual; people, even ‘smart, informed’ people, still think Farset’s some kind of for-profit corporate with loads of money. So I made a tweak

minor tweak cus ppl still dont get that were a charity

---

about/child_protection.md

Bloody DHSSNI changing it's bloody links and not bloody telling anyone; it's not like this shit is important or anything...
Also HTTPS

Fix broken / insecure links

---

assets/css/fsl-style.css

#131 Nothing like a 3 year old bug.

since we never used the flexslider arrows, get rid of em

---

support/index.md

Fix donate link

---

.gitmodule

remove unused submodule file

---

support/index.md

Add info re Amazon Smile and some minor text updates, as it wasn't exactly clear that we accepted one-shot bacs donations.

adding a smile to peoples browsers

---

_config.yml
about/net_conf.md

remove links to wiki

---

_includes/pages/footer.md

Swap Charity / Company designation in footer
Also Add links to charities commission and companies house

charitybeforecompany

---

_config.yml
_layouts/default.html

While foundicon doesn't have a slack (yet), this will do for now unless someone wants to get fancy with logos.

add chat logo to layout

---

about/net_conf.md

https://github.com/FarsetLabs/somebody-should/issues/10

Removed Beta Site and Seltzer from net_conf

---

about/clearance.md
about/rules_and_policies.md

Placeholder for clearance text, for property with known owners.

Add initial work on a clearance policy

---

about/index.html

Remove "Get in touch" links.

---

Dockerfile
README.md
makefile

Dockerfile added to simplify development process. Instructions for how to run are in the README and a makefile command has been added (`make docker`)

Added Dockerfile for development. Updated README and Makefile

---

membership/index.md

Reverts FarsetLabs/farsetlabs.github.io#209

Revert "Removed "Mail handling" from membership benefits."

---

_config.yml
_includes/pages/about_farset.md
_layouts/default.html

Fix slack link as per PR 211

---

dashboard.html

Pushing through to test the hardware, happy to revert later, not "linked to" by anything

really basic dashboard for front-porch display

---

events/coderdojo.md

Just a call-to-action mailing list for Dojo restarting

dojo subscribe form

---

_layouts/default.html
index.html

Adjusting COVID-19 banner styles.
Before | After
--- | ---
Before | After
--- | ---

[COVID-19] Update Banner Styling

---

_layouts/default.html

Update the COVID-19 information banner with the latest statement.
Before | After
--- | ---

[COVID-19] Update Informational Banner

---

hotdesk/index.html

Disable the PayPal button and add some informational text.
Before | After
--- | ---

[COVID-19] Pause Visitor Pass Sales

---

index.html

Update font weight (and link alignment) in the "Get Involved" section to reduce variety of font styles on the homepage.
Before (bold) | After (normal)
--- | ---

[HOMEPAGE] Update Text Styles in "Get Involved" Section

---

_layouts/default.html
assets/css/main.css
index.html

Update font weight used for describing Farset Labs to reduce variety of font styles on the homepage.
Before | After
--- | ---

[HOMEPAGE] Update Text Styles for Farset Labs Description

---

hotdesk/index.html

##
Add missing period to end of final paragraph.
Before | After 
--- | ---

[ISSUE-239] - Add missing period

---

about/facility.md

Renovations saw an end to the majestic blackboard. 😭

Remove the blackboard from the list of facilities.

---

support/equipment.md

Add missing period on equipment donations page. Closes #241
Before | After
--- | ---

[ISSUE-241] Add Missing Period

---

pull_request_template.md

[ISSUE-247](https://github.com/FarsetLabs/farsetlabs.github.io/issues/247)
Adding a GitHub pull request template.
Before | After
--- | ---

[ISSUE-247] Add a GitHub Pull Request Template

---

_config.yml
about/facility.md
about/index.html
index.html
membership/index.md
support/corporates.md
support/equipment.md
support/index.md

Fix issues with inconsistent use of grammar.

---

membership/index.md

Remove broken link.

---

_layouts/default.html

[ISSUE-249](https://github.com/FarsetLabs/farsetlabs.github.io/issues/249)
Added an id in html to the github fork button, to link a media query up to.

Fix issue #249

---

_layouts/default.html

[ISSUE-254](https://github.com/FarsetLabs/farsetlabs.github.io/issues/254)
Added an icon along the top which leads to Farset's twitch page.
Before | After
--- | ---

Embed the Twitch Stream on the Website #254

---

_config.yml
_layouts/default.html

No user-facing changes.
The `_config.yml` file lists all our global variables for reference around the codebase. The references to social media links weren't consistent between full URLs, partial URLs and usernames being listed.
Let's create consistency in this part of the configuration file.

[No Issue] Standardise Social Links in Configuration

---

_config.yml
_layouts/default.html

[ISSUE-263](https://github.com/FarsetLabs/farsetlabs.github.io/issues/263)
Update social icons. Have only updated the Slack icon and added Instagram as attempting to add any more results in it looking too cumbersome.
Before | After
--- | ---

Fixes #263

---

_layouts/default.html
coronavirus.md
covid-19.md
hotdesk/index.html
membership/index.md

Closes #277.
Create a Coronavirus information page for members and visitors that will be kept up to date and reviewed periodically.
Additionally...
* Update header link
* Update link visitor pass purchase
* Update link under membership purchase
New Page |
--- |
Before | After
--- | ---

[ISSUE-277] Create Coronavirus Information Page

---

coronavirus.md

Need to communicate when we last reviewed our covid19 status; i.e. "We haven't changed since X but we last reviewed it Y"
Before | After
--- | ---

Add 'last reviewed' line

---

coronavirus.md

Fixes @awflwafl's comment on #283

Remove "last updated" line

---

_layouts/default.html
assets/css/main.css

Using latest icons, and consistently sourcing them from Font Awesome 5.
Before | After
--- | ---

[No Issue] Use Consistent Icons

---

about/CCTV.md
about/rules_and_policies.md

Addition of our agreed CCTV policy to support our ICO compliance on the use of CCTV for security purporses.

CCTV Policy

---

about/coronavirus_return_policy.md
coronavirus.md

* Updates Coronavirus status as per mgmt meeting 15th June
* Added Coronavirus [Return Document](https://docs.google.com/document/d/1B6HS9ga88qhfSyDOIvXL8sl48xn-9EFcJcfSVV7OlvE/edit#) as reviewed after that meeting

COVID Return Policy and Updates

---

_layouts/default.html

Pride is over... until next year!

Depridefication 2020

---

coronavirus.md

* Clarify public events vs. hackerspace meetings
* Add FAQ answer about wearing masks in the space
* Link to return policy under each stage.

[No Issue] Updating Coronavirus Information Page

---

hotdesk/index.html
membership/index.md

I forgot to update these earlier.
Before | After
--- | ---

[No Issue] Update Coronavirus Notice on Join and Visit Pages

---

farsetlabs.json

add SapceAPI JSON #41
[ISSUE-41](https://github.com/FarsetLabs/farsetlabs.github.io/issues/41)
Add SapceAPI JSON #41
Before | After
--- | ---

add SapceAPI JSON #41

---

farsetlabs.json

[(Example) ISSUE-41](https://github.com/FarsetLabs/farsetlabs.github.io/issues/41)
fix brackets typo
Before | After
--- | ---

fix brackets typo

---

farsetlabs.json

[(Example) ISSUE-41](https://github.com/FarsetLabs/farsetlabs.github.io/issues/41)
comma (3rd time lucky)
Before | After
--- | ---

comma (3rd time lucky)

---

_config.yml
about/index.html

DP and CW resigned from their Digital Infrastructure and Community positions.
Before | After
--- | ---

[No Issue] Transfer DP and CW from Current to Former Officers

---

about/rules_and_policies.md

During #294 upstream links were not reviewed properly.

Update Link that was missed in #294

---

coronavirus.md

Amend Mismatch of Yes/No and ✅/❌.
Before | After
--- | ---

[No Issue] Amend Mismatch of Yes/No and ✅/❌

---

assets/css/main.css

Adjusting the styling to make spacing between icons consistent.
Before | After
--- | ---

[No Issue] Adjust Social Media Icon Layout

---

coronavirus.md

Updating to allow **visitors** back into the space under members' supervision at step 3 of easing out of lockdown. This has been discussed at a few meetings.

Update COVID-19 Plan Regarding Visitors

---

coronavirus.md

Move to step 3 of easing out of lockdown.

Update COVID-19 Plan to Phase 3

---

about/club_mate.md

Cross linking to [this form](https://docs.google.com/forms/d/1fUgrvDnktPW1WM3YsBpFMWUZP5qGrD7Ktu1vsmCVp4s/edit) as a call to action, along with updated stock info from Repeat Drinks

Brexit Reorder Pricing Update and CTA to Form

---

coronavirus.md

After looking at the latest guidance and discussing it at the town hall, we're ready to bring in guests. Still waiting on 👍 from a couple of people before deploying.

Update Coronavirus Status to Step 3

---

coronavirus.md

It's time to go to _Step 5_.
[Latest restrictions for Northern Ireland](https://www.nidirect.gov.uk/articles/coronavirus-covid-19-regulations-guidance-what-restrictions-mean-you) allow indoor gatherings in non-domestic settings (events), so let's update our guidance for members and visitors to reflect it.
> Indoor gatherings (excluding private homes)
> To determine the maximum number of people permitted to attend an indoor gathering, in a non-domestic setting, the organiser or operator must carry out a risk assessment.
> 
> Indoor gatherings of 15 people or fewer do not need a risk assessment.
> 
> The organiser must also take all reasonable measures to limit the risk of transmission of the coronavirus.
> 
> A person responsible for organising a gathering must, if requested to do so by a …

Update Coronavirus Status to Step 5

---

coronavirus.md

I forgot to remove this text after adding the guidance on 15 people limits and risk assessments. In terms of guidance for remote participation, I'll propose it in a separate pull request.

Update COVID-19 Information on Events

---

_layouts/default.html

[(Example) ISSUE-247](https://github.com/FarsetLabs/farsetlabs.github.io/issues/247)
_Example: Add missing period on equipment donations page._
Before | After
--- | ---

Pride 2021

---

_config.yml
about/index.html

Adding pronouns for directors and NEMs profiles.
I'm terrible at CSS. It's honestly a black art to me.
I played around for over an hour trying to style this better but failed miserably. I am only uploading this as a placeholder and show of intention.

Add pronouns for Directors and NEMs

---

_layouts/default.html

Reverts FarsetLabs/farsetlabs.github.io#338
`<satire>`
Happy July everybody, and as is traditional, we expell all the LGBTQI+ people that we publicly permitted to exist for a month and send them back to the reeducation camps
`</satire>`
As always, Farsets [Equality Policy](https://www.farsetlabs.org.uk/about/equality.html) is still in effect. 🏳️‍🌈

Revert "Pride 2021"

---

coronavirus.md

Updating instruction to clarify what we're doing. At first we had online video calls, but moved all instructions online so it can be done self-serve.

Clarify Latest COVID-19 Onboarding Instructions

---

projects.md

Adding a link to our projects to the main navigation. It will redirect to https://trello.com/b/E0E5a6YA/farset-labs-public.

Link to Projects in Main Navigation

---

about/facility.md

Thanks to [DigitalStrata](https://twitter.com/DigitalStrada/status/1433520578460360704) we've a 3D model! 🥳 
Attempted to set the viewport to be more 'iso/front' than the original.

Using the new Matterport scan from Digital Strada

---

membership/index.md

Now that we've been using Nexudus for a while with existing members, let's direct new members to it. Easier for members to manage their own memberships, booking capabilities and more are available on Nexudus.

Direct People to Sign Up on Nexudus

---

assets/css/main.css
index.html

Updates the 3D tour embed so it responds to screen size.

Add responsive styles to the 3D tour

---

coronavirus.md

_Updates due to ending of restrictions._

Updates due to end of restrictions

---

coronavirus.md

_For some reason they show OK in preview but not live_

Fixed URL links

---

about/member_handbook.md

Point to Github Pages hosted member handbook.

Member Handbook Ref

---

_layouts/default.html

Pride; Standard `-logo` addition.

Pride 2022

---

_layouts/default.html

Reverts FarsetLabs/farsetlabs.github.io#370

Revert "Pride 2022"

---

events/coderdojo.md

Mailchimp defunct, remove invalid form

Mailchimp Gone Anyway.

---

projects.md
store.md

Add store page linked from nav bar

---

events/how-to-start-a-class.md

It was decided to lift the pricing (unchanged since 2013) by £5 at the April board meeting.

Booking updates as per April board meeting

---

support/index.md

Update Support Page to have Benevity Link

---

_layouts/default.html

Reverts FarsetLabs/farsetlabs.github.io#394

Revert "Pride 2023"

---

_config.yml
about/who_we_are.html

Thank you for your 13 years of service @andrewbolster.

Andrew has stood down as a director.

---

_config.yml
assets/css/main.css
index.html

Another update from the marketing jams is to add the Nexudus plans to the homepage.
I sort of think it looks a little busy so possibly there's something neater we can do with it, if anyone has ideas.

Add membership plans to homepage

---

_config.yml
about/who_we_are.html
assets/css/main.css
assets/iridium/iridium.css
index.html
support/donate.md

Reverts FarsetLabs/farsetlabs.github.io#418

Revert "Add Stripe pricing table to homepage"
