FarsetLabs/farsetlabs.github.io

- _includes/google_analytics.html
Sorry, it looks like google plus verification is literally looking for the string "<a href="https://plus.google.com/+FarsetlabsOrgUk" rel="publisher">Google+</a>" rather than walking the DOM for a publisher link.
> GPlus Sucks

- about/child_protection.md
- about/code_of_conduct.md
- about/facility.md
- about/hardware_donation_license.md
- about/index.html
- about/rules_and_policies.md
Giving AD-73 a go; also includes weighting tweaks to normalise order of listings under About, clean up some cruff from the about page, and in general clean things up just a little.
Summarises pretty much all the rules under one page, as well as cleaning up some of the links, particularly in the CPP, and matching button types in the about page.
> AD-73 Attempt

- _config.yml
Updated GH Jekyll plugins;
https://help.github.com/articles/using-jekyll-plugins-with-github-pages/
Includes new github-compatible [emoji](https://github.com/jekyll/jemoji), [GH mentions](https://github.com/jekyll/jekyll-mentions) and markdown-based [redirection](https://github.com/jekyll/jekyll-redirect-from) which should be really useful to maintaining links in the future.
> include updated available jekyll plugins

- about/ops_manual.md
Updating Ops Manual to realistically reflect current and upcoming NEMS roles: 
Of particular note is the dissolution of Projects NEM, being folded into the Project Room NEM, as well as the dissolution of Facilities position and the creation of an Outreach Nem
> Update to NEMS Roles

- about/rules_and_policies.md
- about/sponsored_membership_policy.md
- membership/index.html
Also includes crosslinks to membership page, updates membership emails to join@farsetlabs.org.uk to deconflict with proposed members@farsetlabs.org.uk email list.
> Sponsored Membership Policy

- README.md
The `develop` branch is going - we don't have an effective workflow for beta testing yet, and when we do, it'll be feature branch deploys, not a staging server. We are not a Fortune 100 company.
> Correct documentation for develop branch removal

- _config.yml
- _layouts/default.html
Google+ is soon to be dead.
https://www.blog.google/technology/safety-security/project-strobe/
> remove google+ social icon

- about/charitable_aims.md
Added a new page under About to detail the aims of Farset as a
registered charity in NI.
Taken directly from the Charity Commission's website:
https://www.charitycommissionni.org.uk/charity-details/?regId=102754&subId=0
Fixes #204
> Added a new page outlining the aims of the charity.

- _config.yml
Jekyll was complaining about the _config.yml having the sitename
configured as site.name instead of site.title as many plugins and themes
expect it to be.
> Update GitHub metadata.

- slack/index.md
If a user browses to /slack they will now be redirected to
https://slackin.farsetlabs.org.uk/
"How do I access the Slack?
If you just go to the website farsetlabs.org.uk forward slash slack it should direct you to a page to sign-up."
Provides a way to be able to offer a simple direction to someone asking about how to access the Slack.
> Provide a redirect to the Slack sign-up page.

- about/index.html
- events/index.md
- hotdesk/index.html
- membership/index.md
- support/index.md
Splits out "Visit" into its own navigation item because it's not intuitive to find a one-time day pass under "Join".
Before | After
--- | ---
> [NAVIGATION] Split Out "Join" and "Visit" Options

- _layouts/default.html
- assets/css/main.css
Override some styles to make the photo slides look clean and flush with the page layout.
Before | After
--- | ---
> [HOMEPAGE] Override Carousel Styling

- assets/css/main.css
[ISSUE-249](https://github.com/FarsetLabs/farsetlabs.github.io/issues/249)
Added a relevant media query to make fork me button disappear on smaller viewports.
Before | After
--- | ---
> Issue #249 part 2

- _config.yml
There are two "Blog" links in the navigation and one of them was pointing at the RSS feed, which was counterintuitive.
There is a separate RSS feed link.
Before | After
--- | ---
> [No Issue] Correct Blog Link

- about/contributors.html
- assets/css/main.css
[ISSUE-260](https://github.com/FarsetLabs/farsetlabs.github.io/issues/260)
Add a "Contributors" page under the "About" section showing all contributors to our website.
Closes #260.
Desktop |
--- |
Mobile | 
--- |
> [ISSUE-260] Show Contributors to the Website on the Website

- about/contributors.html
[(Example) ISSUE-247](https://github.com/FarsetLabs/farsetlabs.github.io/issues/247)
'website' spelt incorrectly on Contributors page
Before | After
--- | ---
`s/wesite|website/g`
> Spelling Mistake

- _includes/pages/footer.md
- _layouts/default.html
- assets/css/main.css
Closes #276.
At the moment landing on our website on mobile shows our header taking up between 1/3 and 1/4 of the screen Let's move our overpopulated social media icons into the footer to prevent them breaking layout. 
Additionally, adjusting footer layout.
Before | After
--- | ---
> [ISSUE-276] Adjust Header and Footer

- Dockerfile
- Gemfile.lock
The base docker image installs bundler `2.0.2`, so the bundle command fails because it can't find a version 1 bundler installation.
Update the version in the `gemfile.lock` file to match the installed version.
> Update bundler version and pin docker base image version

- _config.yml
[(Example) ISSUE-247](https://github.com/FarsetLabs/farsetlabs.github.io/issues/247)
Let's clear up the top navigation.
Our top navigation bar is a bit cluttered and we've already got social links displayed in the website footer, which is the common approach these days.
Before | After
--- | ---
> [No Issue] Remove Social Links from Navigation Bar

- _layouts/default.html
Closes #267.
Let's add a link to "edit this page on GitHub". I've seen this done on a bunch of community maintained websites (mostly for open source projects).
Easier on-the-fly edits to the website and lower technical barrier to suggesting edits.
Before | After
--- | ---
> [ISSUE-267] Add "Edit this page on GitHub" Link to All Pages

- coronavirus.md
Fixes the strikethroughs on steps 3 and 4 of the covid information page.
Before | After
--- | ---
> Fix strikethroughs on the COVID page

- _config.yml
- _includes/pages/about_farset.md
- _layouts/default.html
- coronavirus.md
- farsetlabs.json
- slack/index.md
[Take down public Slack link](https://trello.com/c/2RBxXh0S/75-take-down-public-slack-link)
In the past month we've had 3 spammers joined our Slack, and in general some people find us and join the Slack for a day and never signing in again. We have a limit of 250 members under the charity tier, before we need to start paying per member.
Let's take down the public Slack link and see if this helps, if it doesn't we can look at taking down the auto-inviting app, too.
> Remove Slack Link from Website

- _config.yml
We are moving towards segmenting roles & responsibilities, rather than everybody needing to know everything on an ad-hoc basis. Our roles are taken from the DIY Committee guidance, and we'll be figuring out their implementation for Farset Labs over the current quarter.
* Art, [Chair](https://www.diycommitteeguide.org/code/principle/what-role-chairperson)
* Dylan, [Treasurer](https://www.diycommitteeguide.org/resource/what-role-treasurer)
* Andrew, [Secretary](https://www.diycommitteeguide.org/resource/what-role-secretary)
> Show board roles on our website

- member-handbook.md
Adding a link to the Member Handbook from the website. Navigation will shift and need adjusting.
> Add Member Handbook to Navigation

- member-handbook.md
Reverts FarsetLabs/farsetlabs.github.io#363
Breaks nav layout and raises a cert failure on clickthrough.
> Revert "Add Member Handbook to Navigation"

- index.html
Reviewed Locally.
Consensus on #389 required to replace, but also don't want a blank space on the website.
> Remove Matterport IFrame and revert to original carousel

- _config.yml
- store.md
Replaces the embedded Ecwid store with a link to our Spreadshop.
You _can_ embed a Spreadshop but it literally displays the entire page in the frame and it doesn't look very good and I don't have time to try to optimise the shop to make it work, so this feels like a decent tradeoff.
Before | After
--- | ---
> Replace Ecwid store with Spreadshirt shop

- index.html
- shop/club_mate.md
Quick follow-up fixes
* Formatting the markdown variables on the clubmate page made Jekyll confused (probably because it’s after some HTML), so revert this.
* Remove trailing `/` from events — Github pages / Jekyll doesn’t support this and they’re 404ing
> Remove trailing slash to fix event links

- farsetlabs.json
- index.html
Removes the phone number from the website. Although it is still active, it's not regularly monitored.
> Remove phone number

- redirects/3d-printers.md
- redirects/cnc-machine.md
- redirects/laser-cutter.md
- redirects/resin-printers.md
- redirects/slack.md
Adds a set of redirects, which we can use on internal signage but allows changing in the future.
Redirecting to these pages:
- https://www.farsetlabs.org.uk/member-handbook/rooms/workshop/training#3d-printers
- https://www.farsetlabs.org.uk/member-handbook/rooms/workshop/FoxAlienCNC
- https://www.farsetlabs.org.uk/member-handbook/rooms/workshop/training#laser-cutter
- https://www.farsetlabs.org.uk/member-handbook/rooms/workshop/resin_printers
- https://farsetlabs.slack.com/
Preview of redirects:
- https://deploy-preview-410--storied-crostata-fa92db.netlify.app/workshop/3d-printers/
- https://deploy-preview-410--storied-crostata-fa92db.netlify.app/workshop/cnc-machine/
- https://deploy-preview-410--storied-crostata-fa92db.netlify.app/workshop/laser-cutter/
- …
> Adds shorter URLs to be used in QR codes on internal signage

- _config.yml
- _layouts/default.html
Adds a link to LinkedIn to the social links in the footer.
Remove the hyperlink from the theme author's name in the footer. It's a dead link, can't find a working one for the same person.
> Footer updates

- _layouts/default.html
Fixes #411 
Fixes the hamburger menu on mobile. For some reason it just needed the word `Menu` to be contained within a span. I assume something is adding an `:after` rule to it somewhere but I can't quite figure out what.
Before | After
--- | ---
> Fix menu icon on mobile

- login/index.md
- membership.md
Adds links to Stripe and Nexudus to a `/login` page. Before `/login` just redirected you straight to Stripe but many people are still on Nexudus (and people find it hard enough as it is to find Nexudus when they need it).
> Add both Stripe and Nexudus options to login page
